### ISSUE TITLE
Validator namespace

### ISSUE THREAD

**Issue by lewispb** [DEFRA/ea-validation#6]
We can avoid the ugly:

`validates :company_name, "ea/validation/companies_house_name" => true`

and have it like this:

`validates :company_name, companies_house_name: true`

We would have to move the validators into the ActiveModel::Validations namespace though. Thoughts? @autotelik @Cruikshanks  

Ref: http://stackoverflow.com/questions/6058253/rails3-doesnt-load-my-validators-in-lib

**Comment by autotelik** [comment]
i don't think namespaces are ugly - to avoid clashing with other validations people might want to bring in, or write, don't you think  we should use something like an'EA'  module

**Comment by kennyevil** [comment]
Agree with @lewispb on this. His suggested namespacing follows Rails convention whereas the current namespacing doesn't. If there's an issue with clashing validations, we can cross that bridge when we get to it but I think that's unlikely. Even if that does happen, that's what Pull Requests are for and it's up to the person bringing in the new validations to ensure it doesn't conflict with existing ones.
