### ISSUE TITLE
Error messages produce translation errors

### ISSUE THREAD

**Issue by irisfaraway** [DEFRA/ea-validation#8]
The gem provides I18n config for validation error messages: https://github.com/DEFRA/ea-validation/blob/master/config/locales/error.en.yml

However, when using the gem in a Rails app and using the hint text, you get a `I18n::MissingTranslationData` error.

For example: `translation missing: en.ea.validation.errors.companies_house_number.hint`

This can be fixed by copying the I18n file into the Rails app.

However, if you trigger a validation error, it looks for the message against the field name (in this case `company_no`):

`translation missing: en.ea.validation.errors.companies_house_number.company_no.invalid_html`

Which requires you to add the I18n text for that specific field.

**Comment by Cruikshanks** [comment]
This gem has been replaced by [Defra ruby validators](https://github.com/DEFRA/defra-ruby-validators).
